import { PortfolioItem, ActiveProject, AgentManifest } from "./types";

export const PORTFOLIO_DATA: PortfolioItem[] = [
  {
    id: "lumina-2027",
    title: "CALIFORNIA BANK & TRUST (OFFICIAL BANK OF SAN DIEGO FC)",
    client: "California Bank & Trust",
    category: "The Impact",
    aspectRatio: "2.39:1",
    videoDuration: "1:45",
    role: "Producer",
    thumbnailUrl: "/src/assets/images/calbank_cover_sdfc_1781669075922.jpg",
    director: "Marcus Vance",
    cinematographer: "Evelyn Kross",
    budgetGrade: "Tier-1 (Premium)",
    cameraPackage: "ARRI Alexa Mini LF",
    lensesUsed: "Cooke Anamorphic/i SF Prime Set",
    colorSpace: "Arri log-C4 (ACES workflow)",
    releaseYear: "2027",
    synopsis: "Official Category Partnership of MLS Club. A high-end commercial presentation capturing the spirit of institutional support, sporting excellence, and community trust in San Diego.",
    projectStory: "We partnered with San Diego FC and California Bank & Trust to create a film that represents solidarity rather than standard commercial transaction. By focusing on local community integration, the warmth of the fans, and state-of-the-art cinematic lighting, we delivered an authentic visual message of modern financial partnership.",
    technicalCraftDetails: "Shot in high-dynamic-range with custom LUT configurations on location. Post-production pipeline graded in ACES 1.3 color space to preserve optimal shadow clarity and vivid colors.",
    resultImpact: "Recognized as a premier partnership campaign, establishing a powerful emotional connection among San Diego sports fans and financial stakeholders.",
    moodTags: ["Strategic", "Community", "Institutional", "Premium", "Dynamic"],
    vimeoVideoId: "1202329639"
  },
  {
    id: "sdfc-emergence-anthem",
    title: "SAN DIEGO FC: EMERGENCE (CLUB ANTHEM)",
    client: "San Diego FC",
    category: "The Impact",
    aspectRatio: "2.39:1",
    videoDuration: "2:15",
    role: "Director / DP",
    thumbnailUrl: "https://images.unsplash.com/photo-1518063319789-7217e6706b04?auto=format&fit=crop&q=80&w=1200",
    director: "Marcus Vance",
    cinematographer: "Evelyn Kross",
    budgetGrade: "Tier-1 (Premium)",
    cameraPackage: "ARRI Alexa 35",
    lensesUsed: "Cineovision Anamorphic Primes",
    colorSpace: "Arri Log-C4 (ACES workflow)",
    releaseYear: "2027",
    synopsis: "The official launch film capturing the deep-rooted spirit, soccer heritage, and emergence of San Diego's MLS franchise.",
    projectStory: "Shot over three weeks across diverse neighborhoods in San Diego, this cinematic anthem captures the emotional resonance of the beautiful game. From the beaches of Coronado to local community pitches and the grand Snapdragon Stadium, we celebrated the intersection of youth culture, community pride, and sporting excellence.",
    technicalCraftDetails: "Captured in ultra-high resolution using the ARRI Alexa 35 with vintage Cineovision Anamorphic lenses to offer a nostalgic yet ultra-crisp image quality. The grade was handled with custom-designed print emulation profiles to emulate Kodak 500T 5219 film stock, creating beautiful skin tones and saturated golden-hour flares.",
    resultImpact: "Critically acclaimed across sports media channels. Achieved over 5 million organic digital views within 48 hours of launch, and played on the giant screens during the inaugural home match.",
    moodTags: ["Anthemic", "SDFC Club Heritage", "Community Pride", "Anamorphic Nostalgia", "Stunning Sunsets"],
    vimeoVideoId: "1201989026"
  },
  {
    id: "vimeo-spa-ritual",
    title: "SPA RITUAL: THE ART OF STILLNESS",
    client: "Spa Ritual Wellness",
    category: "The Impact",
    aspectRatio: "16:9",
    videoDuration: "1:30",
    role: "Director / Editor",
    thumbnailUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=1200",
    director: "Aya Tanaka",
    cinematographer: "Evelyn Kross",
    budgetGrade: "Tier-2 (Mid-Range)",
    cameraPackage: "Sony Venice 2",
    lensesUsed: "Atlas Orion Anamorphic Primes",
    colorSpace: "ACES workflow (S-Log3)",
    releaseYear: "2027",
    synopsis: "New Spa Property Branding. A luxurious visual odyssey centering on raw geothermal waters, quiet stone textures, and tactile wellness.",
    projectStory: "This piece for Spa Ritual redefines modern luxury commercial guidelines by slowing the edit down to match the physiological state of decompression. We lit each steam chamber with specialized custom LEDs matched to the frequency of natural candlelight, ensuring the slow-motion water droplets catch crisp, authentic sparkles.",
    technicalCraftDetails: "Captured at 60fps on the Sony Venice 2 dual-base ISO sensor to preserve rich shadow detail in steam-filled chambers without introducing digital noise. The color grade emphasizes soft warm tones and rich natural hues.",
    resultImpact: "Elevated the hotel's digital profile, securing triple the standard booking interest and establishing a new gold standard in sensory hospitality cinema.",
    moodTags: ["Spa Ritual", "Tactile Wellness", "Geothermal Waters", "Minimalist Lux", "Deep Decompression"],
    vimeoVideoId: "1201988409"
  },
  {
    id: "vimeo-ahead-of-the-curve",
    title: "AHEAD OF THE CURVE: BIOMECHANIC FLOW",
    client: "Biomechanic Fitness",
    category: "The Impact",
    aspectRatio: "16:9",
    videoDuration: "1:15",
    role: "Co-Director / Colorist",
    thumbnailUrl: "/src/assets/images/biomechanic_flow_cover_1781670049518.jpg",
    director: "Marcus Vance",
    cinematographer: "Leo Thorne",
    budgetGrade: "Tier-1 (Premium)",
    cameraPackage: "ARRI Alexa 35",
    lensesUsed: "Cooke Anamorphic/i SF",
    colorSpace: "Arri Log-C4 (ACES workflow)",
    releaseYear: "2027",
    synopsis: "New Product Release. A gorgeous, cinematic showcase of modern kinetic wellness and high-tech biomechanical training.",
    projectStory: "This high-end cinematic launch film introduces a revolutionary elliptical training machine. We tracked the athlete's athletic motion with real-time HUD overlays, casting soft warm light across a luxury penthouse view during a bright morning walk-through.",
    technicalCraftDetails: "The Alexa 35's unmatched dynamic range allowed us to pull back extreme window highlights while keeping the internal room tones elegantly warm. Custom HUD graphic elements were tracked precisely in post-production using real biomechanical reference points.",
    resultImpact: "The campaign drove unprecedented product launch interest, setting a brand-new standard for commercial kinetic design globally.",
    moodTags: ["Ahead of the Curve", "Kinetic Wellness", "Biomechanical HUD", "Penthouse Sunset Glow", "High-End Training"],
    vimeoVideoId: "1201987707"
  },
  {
    id: "vimeo-sycuan-health",
    title: "SYCUAN HEALTH CENTER: COMMUNITY GUARDIANS",
    client: "Sycuan Health",
    category: "The Truth",
    aspectRatio: "16:9",
    videoDuration: "3:40",
    role: "Director / DP",
    thumbnailUrl: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=1200",
    director: "Elena Rostova",
    cinematographer: "Elena Rostova",
    budgetGrade: "Tier-2 (Mid-Range)",
    cameraPackage: "Sony FX6",
    lensesUsed: "Sony G Master Primes",
    colorSpace: "Sony S-Cinetone",
    releaseYear: "2026",
    synopsis: "Health Care. An intimate documentary look at the dedicated community health professionals keeping families safe and healthy.",
    projectStory: "Filmed over several weeks, we wanted to capture the heart of the Sycuan Health Center team. By using native lighting and minimal rig footprints, we stayed out of the way, allowing authentic patient interactions, community wellness efforts, and professional dedication to take center stage.",
    technicalCraftDetails: "Shot using an agile Sony FX6 package optimized for fast transitions. S-Cinetone was selected to create warm, appealing skin tones natively in-camera, eliminating heavy post-production times.",
    resultImpact: "Built a massive trust index within the local county networks, receiving high acclaim from medical associations and community leaders alike.",
    moodTags: ["Sycuan Health", "Community Guardians", "Empathy", "Wellness", "Authentic Documentary"],
    vimeoVideoId: "1201987331"
  },
  {
    id: "vimeo-drakes",
    title: "DRAKE'S: SAVOR & SILHOUETTE",
    client: "Drakes Restaurant",
    category: "The Impact",
    aspectRatio: "2.39:1",
    videoDuration: "1:40",
    role: "Director / DP",
    thumbnailUrl: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&q=80&w=1200",
    director: "Sion Jenkins",
    cinematographer: "Tariq Al-Fayed",
    budgetGrade: "Tier-2 (Mid-Range)",
    cameraPackage: "RED V-Raptor 8K VV",
    lensesUsed: "Laowa Probe Lens & Leica Summicron-C",
    colorSpace: "REDWideGamutRGB",
    releaseYear: "2027",
    synopsis: "Restaurant Branding. An close-up, sensory look at culinary excellence, artisanal plating style, and twilight dining interiors.",
    projectStory: "To establish a premium branding spot for Drake's, we avoided standard restaurant clip trends. We filmed the kitchen in a beautiful stark contrast profile—letting sizzling pan embers light the chef's hands and using a specialized probe lens to dive directly into the intricate layers of a multi-course tasting menu.",
    technicalCraftDetails: "Utilized macro-cinematography combined with high precision LED bars to create unique focal depths inside plates. High shutter-speed sequences capture the rapid flash of seasoning and high-heat chef maneuvers.",
    resultImpact: "Won Best Hospitality Video at the City Culinary Association, serving as a signature digital asset across their digital brand and social landing web-flows.",
    moodTags: ["Drakes Savor", "Artisan Plating", "Macro Plating", "Culinary Shadows", "Tasting Luxury"],
    vimeoVideoId: "1201986300"
  },
  {
    id: "vimeo-malones",
    title: "MALONE'S: A FESTIVE FIRESIDE",
    client: "Malone's Tavern",
    category: "The Impact",
    aspectRatio: "16:9",
    videoDuration: "1:05",
    role: "Producer / Gaffer",
    thumbnailUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=1200",
    director: "Aya Tanaka",
    cinematographer: "Leo Thorne",
    budgetGrade: "Tier-3 (Indie/Agile)",
    cameraPackage: "Sony Venice 2",
    lensesUsed: "Angenieux Optimo Ultra 12x",
    colorSpace: "S-Gamut3.Cine",
    releaseYear: "2026",
    synopsis: "Restaurant Christmas Promo. Warm tavern fires, traditional roasts, and shared joy during a golden holiday evening.",
    projectStory: "Malone's wanted a cozy, cinematic holiday spot that felt like home. We captured the glowing embers of open-hearth cooking, slow-pour pints under vintage Edison lights, and friends gathered under candlelight to create an immersive visual that literally smells like woodsmoke and holiday spices.",
    technicalCraftDetails: "Used a custom warm LUT setup combined with practical gas fires to cast soft golden glows on actors' skin. Handheld camera drifts make the tavern space feel welcoming and deeply personal.",
    resultImpact: "Achieved the highest seasonal tavern bookings on record, establishing a powerful emotional resonance with families across the region.",
    moodTags: ["Malones Feast", "Warm Firesides", "Golden Evenings", "Holiday Glow", "Cozy Dinner"],
    vimeoVideoId: "1201985974"
  },
  {
    id: "vimeo-feeding-sd",
    title: "FEEDING SAN DIEGO: MISSION READY",
    client: "Feeding San Diego",
    category: "The Truth",
    aspectRatio: "16:9",
    videoDuration: "4:15",
    role: "Director / Editor",
    thumbnailUrl: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&q=80&w=1200",
    director: "Elena Rostova",
    cinematographer: "Evelyn Kross",
    budgetGrade: "Tier-3 (Indie/Agile)",
    cameraPackage: "Sony FX6",
    lensesUsed: "Sony GM Zoom & Primes",
    colorSpace: "S-Log3",
    releaseYear: "2027",
    synopsis: "Non-Profit Military Support. An elegant, raw, documentary framing of volunteer efforts supplying nutritious meals to local military and veteran families.",
    projectStory: "Meeting volunteers and military families on site, we chose to utilize natural daylight and warehouse ambient beams. The focus remains on the power of collective hands—assembling fresh produce, the small, quiet smiles of shared bags, and the real-time operational scale behind a crucial community hub.",
    technicalCraftDetails: "Filmed inside busy dispatch bays and distribute zones. We used lightweight standard prime lenses with a native stabilization rig to keep our lens close to the action without disrupting active sorting lines.",
    resultImpact: "The campaign galvanized donation volume, raising over $250k in volunteer funding within a week of release on civic channels.",
    moodTags: ["Feeding San Diego", "Military Support", "Volunteer Hearts", "Documentary Grit", "Hopeful Community"],
    vimeoVideoId: "1201985181"
  },
  {
    id: "vimeo-gameday-iconic",
    title: "GAME DAY ICONIC: SNAPDRAGON STADIUM",
    client: "Snapdragon Fan Spot",
    category: "The Impact",
    aspectRatio: "2.39:1",
    videoDuration: "1:00",
    role: "Lead Cameraman",
    thumbnailUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&q=80&w=1200",
    director: "Marcus Vance",
    cinematographer: "Leo Thorne",
    budgetGrade: "Tier-2 (Mid-Range)",
    cameraPackage: "Phantom Flex 4K",
    lensesUsed: "Atlas Orion Anamorphics",
    colorSpace: "ACES workflow",
    releaseYear: "2027",
    synopsis: "Game Day Iconic. Ultra slow-motion smoke rising from gourmet tailgates, stadium lights beaming, and vibrant team colorways.",
    projectStory: "This high-impact spot was designed to capture the pure energy of game day in San Diego. Rather than focusing just on the pitch, we focused on the physical rituals—the exact snap of cold cans, team paint glowing, slow-motion barbecue grill flare-ups, and the final look up as Snapdragon's lights hum to life.",
    technicalCraftDetails: "We filmed at 1000fps in 4K resolution using the powerhouse Phantom Flex 4K paired with Atlas Orion anamorphic lenses, achieving beautiful stadium bokeh flares and smooth-as-silk slow motion.",
    resultImpact: "Played on stadium displays throughout the SDFC preseason, thrilling fans and driving substantial food partnership revenue.",
    moodTags: ["Snapdragon Iconic", "1000fps Slow Motion", "Stadium Flares", "Tension & Release", "Pure Fan Energy"],
    vimeoVideoId: "1201965320"
  },
  {
    id: "vimeo-farmers-insurance-open",
    title: "TORREY PINES: THE FARMERS INSURANCE OPEN",
    client: "PGA Tour / Century Club",
    category: "The Impact",
    aspectRatio: "2.39:1",
    videoDuration: "2:00",
    role: "Producer / Gaffer",
    thumbnailUrl: "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?auto=format&fit=crop&q=80&w=1200",
    director: "Sion Jenkins",
    cinematographer: "Tariq Al-Fayed",
    budgetGrade: "Tier-1 (Premium)",
    cameraPackage: "ARRI Alexa 35",
    lensesUsed: "Zeiss Supreme Primes",
    colorSpace: "Arri Log-C4",
    releaseYear: "2024",
    synopsis: "San Diego PGA Promo Spot. Coastal ocean mist rolling across legendary Torrey Pines golf course paths, crisp ball strike acoustics, and dawn silhouettes.",
    projectStory: "To film the legendary Farmers Insurance Open, we got to the green at 4:30 AM. Coastal fog rolled off the Pacific, perfectly backlit by the rising sun. Our camera hovered low over the dew-glistening grass to track high-speed balls lifting into beautiful, hazy skies, capturing the architectural design and intense focus of PGA performance.",
    technicalCraftDetails: "We utilized special high-speed zooms combined with the Alexa 35's 17 stops of dynamic range to maintain deep, crisp greens against bright, over-the-ocean morning highlights.",
    resultImpact: "The official PGA broadcast partner showcased this sequence as their primary event opener, driving spectacular viewership ratings.",
    moodTags: ["Farmers Insurance Open", "Torrey Pines Coastal", "Pacific Fog", "Perfect Dawn Silhouettes", "Golf Acoustics"],
    vimeoVideoId: "1201972095"
  },
  {
    id: "vimeo-gameday-illustrator",
    title: "GAME DAY ILLUSTRATOR: SAN DIEGO MURALISTS",
    client: "Chicano Park Muralists",
    category: "The Craft",
    aspectRatio: "16:9",
    videoDuration: "2:45",
    role: "Director / DP",
    thumbnailUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&q=80&w=1200",
    director: "Elena Rostova",
    cinematographer: "Evelyn Kross",
    budgetGrade: "Tier-2 (Mid-Range)",
    cameraPackage: "Sony Venice 2",
    lensesUsed: "Leica Summicron-C",
    colorSpace: "Arri log-C scale conversion",
    releaseYear: "2027",
    synopsis: "Sports Bar & Urban Art Branding. Capturing the raw canvas strokes, paint mist clouds, and communal spirit of muralists celebrating soccer.",
    projectStory: "This piece profiles the creative masterminds spray-painting legendary murals throughout San Diego's creative districts. The camera tracks detailed, sweeping paints, vibrant oil colors, and the sweat of artists pouring their hearts into larger-than-life canvases that welcome the stadium era.",
    technicalCraftDetails: "Using the Sony Venice 2 split-body Rialto 2, we got right under the artist scaffolding to shoot directly from the paint's point of view. High speed framing tracks independent aerosol particles and intense workspace focus.",
    resultImpact: "Lauded by community boards and design guilds; selected as an artistic exhibition feature at the San Diego Modern Museum of Art.",
    moodTags: ["Gameday Illustrator", "Chicano Park Murals", "Aerosol Particles", "Vivid Spray Textures", "Urban Art Legacy"],
    vimeoVideoId: "1201963152"
  }
];

export const ACTIVE_PROJECTS_DATA: ActiveProject[] = [
  {
    id: "chronos-watch-ad",
    name: "CHRONOS - SCIFI TIMEPIECE ANTHEM",
    clientName: "Chronos Horology S.A.",
    status: "Post-Production",
    completionPercentage: 80,
    thumbnailUrl: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&q=80&w=1200",
    nextShootDate: "Completed (Pickup shoots tentative)",
    budgetSpentPercentage: 85,
    budgetTotal: "$120,000",
    director: "Aya Tanaka",
    timeline: [
      { id: "m1", title: "Creative Concept & Script Signoff", status: "completed", description: "Cyberpunk steampunk watch hybrid ad scripting.", dueDate: "2026-04-10", completedAt: "2026-04-09" },
      { id: "m2", title: "Pre-Production & Casting", status: "completed", description: "Location scouting inside decommissioned clock tower.", dueDate: "2026-04-28", completedAt: "2026-04-26" },
      { id: "m3", title: "Principal Photography", status: "completed", description: "3 shooting days with high-speed Phantom Flex 4K camera.", dueDate: "2026-05-15", completedAt: "2026-05-16" },
      { id: "m4", title: "Rough Cut Review", status: "completed", description: "Assembly cut review with client feedback integrated.", dueDate: "2026-05-30", completedAt: "2026-05-29" },
      { id: "m5", title: "Color Grading & Sound Master", status: "current", description: "Integrating ACES grading and custom dynamic synth foley.", dueDate: "2026-06-25" },
      { id: "m6", title: "Final 8K Delivery", status: "upcoming", description: "Dolby Vision deliverables export and final archive.", dueDate: "2026-07-05" }
    ],
    reviewComments: [
      { id: "c1", timestamp: "2026-06-10 14:32", timecode: "00:12.05", timeInSeconds: 12.2, user: "Scott Bernstein (Producer)", avatarColor: "bg-amber-500", text: "Can we extend the glow on the timepiece face? Right now the reflection feels a bit muted as the character turns their wrist." },
      { id: "c2", timestamp: "2026-06-11 09:12", timecode: "00:12.05", timeInSeconds: 12.2, user: "Aya Tanaka (Director)", avatarColor: "bg-sky-500", text: "Good feedback. VFX can paint in a soft linear sweep on the sapphire glass reflection to make it pop.", isResolved: true },
      { id: "c3", timestamp: "2026-06-14 11:20", timecode: "00:45.18", timeInSeconds: 45.72, user: "Scott Bernstein (Producer)", avatarColor: "bg-amber-500", text: "The sub-bass drone here is perfect, but let's drop the ticking sound effect slightly. It competes with the synth pads." },
      { id: "c4", timestamp: "2026-06-15 17:05", timecode: "01:10.02", timeInSeconds: 70.08, user: "Scott Bernstein (Producer)", avatarColor: "bg-amber-500", text: "Make sure the outro logo aligns perfectly with the brand color guideline (#E2C974). Right now it looks a tiny bit warm/reddish." }
    ],
    videoStreamUrl: "https://assets.mixkit.co/videos/preview/mixkit-futuristic-subway-station-with-neon-lights-43953-large.mp4"
  },
  {
    id: "solaria-energy-national",
    name: "SOLARIA ENERGY NATIONAL LAUNCH",
    clientName: "Solaria Renewables Inc.",
    status: "Pre-Production",
    completionPercentage: 40,
    thumbnailUrl: "https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&q=80&w=1200",
    nextShootDate: "2026-06-28",
    budgetSpentPercentage: 35,
    budgetTotal: "$245,000",
    director: "Marcus Vance",
    timeline: [
      { id: "s1", title: "Script Concept Selection", status: "completed", description: "Narrative highlighting local farmers utilizing modern wind/solar tech.", dueDate: "2026-05-10", completedAt: "2026-05-12" },
      { id: "s2", title: "Technical Boarding & Budget Review", status: "completed", description: "Shotlist finalized and equipment package assigned.", dueDate: "2026-05-25", completedAt: "2026-05-24" },
      { id: "s3", title: "Scouting & Permit Clearances", status: "current", description: "Securing drone flyover permits for the Mojave solar plant arrays.", dueDate: "2026-06-20" },
      { id: "s4", title: "Principal Photography", status: "upcoming", description: "4-day travel shoot covering Desert, Coastline, and Lab environments.", dueDate: "2026-06-28" },
      { id: "s5", title: "VFX & Compositing Block", status: "upcoming", description: "Superimposing renewable data models onto clean energy grids.", dueDate: "2026-07-20" },
      { id: "s6", title: "Final Deliverables & Search Optimization campaign launch", status: "upcoming", description: "Optimized video crops for search-ready digital distribution channels.", dueDate: "2026-08-15" }
    ],
    reviewComments: [
      { id: "sc1", timestamp: "2026-06-05 10:00", timecode: "00:00.00", timeInSeconds: 0, user: "Scott Bernstein (Producer)", avatarColor: "bg-amber-500", text: "The storyboard drafts were phenomenal! Please ensure the aerial drone director follows the exact sweeping angle of option B." }
    ],
    videoStreamUrl: "https://assets.mixkit.co/videos/preview/mixkit-wind-turbines-on-a-grass-covered-hill-41710-large.mp4"
  }
];

export const AGENT_MANIFEST_DATA: AgentManifest = {
  companyName: "HARD RAIN PRODUCTIONS",
  producerName: "Scott Bernstein (Executive Producer & Owner)",
  specialties: [
    "High-End Luxury Brand Commercials",
    "Independent Narrative & Feature Pitching",
    "Virtual Production & LED Volume Cinematography",
    "Digital Optimization for Dynamic Search Visibility (SEO Video Strategies)",
    "Frame-Accurate Real-Time Client Portal Tracking"
  ],
  operationalRegions: ["San Diego, CA (HQ)", "Los Angeles, CA", "Global Scope", "New York", "London", "Tokyo"],
  contactEmail: "scott.hardrain@gmail.com",
  contactPhone: "+1 (619) 961-8445",
  vimeoUrl: "https://vimeo.com/user148624521",
  cameraPackages: [
    "ARRI Alexa 35 & Alexa Mini LF",
    "Sony Venice 2 with Rialto Extension System",
    "RED V-Raptor XL 8K",
    "Phantom Flex 4K (Ultra Slow Motion Specialists)"
  ],
  postProductionCapabilities: [
    "DaVinci Resolve Studio color grading via ACES 1.3 standard",
    "Houdini & Unreal Engine 5.5 Visual Effects Compositing",
    "Spatial Audio & Dolby Atmos Dynamic Mixing"
  ],
  faqs: [
    {
      category: "Search Optimization & Metadata",
      question: "How is your video production platform optimized for modern search engines and discovery channels?",
      answer: "We structure all production assets, scripts, credits, and post-production logs with valid JSON-LD schema markup, descriptive semantic transcripts, and specialized machine-readable metadata. When search crawlers scan your project, they immediately understand the direct client, key team members, equipment, technical specifications, and stylistic descriptions, ensuring your content is accurately referenced and recommended as a top-tier visual benchmark."
    },
    {
      category: "Cooperation & Booking",
      question: "What is your typical production workflow and how do client reviews work?",
      answer: "We utilize our highly integrated client portal. Every project gets a dedicated workspace outlining the timeline of milestones (Scripting, Prep, Shooting, Edits). Once an edit is uploaded, clients can scrub through frame-by-frame and log timecode-specific comments. This avoids email sprawl and guarantees our post-production operators can work with absolute surgical accuracy."
    },
    {
      category: "Pricing & Budgets",
      question: "What budget tiers do you work with?",
      answer: "We structure projects into three tiers: Tier-1 (Premium) for complex multi-location brand ads or Virtual Volume projects starting at $150k; Tier-2 (Mid-Range) for national campaigns and music videos ($50k-$150k); and Tier-3 (Agile/Indie) for quick organic teasers, sleek social briefs, or documentary shorts utilizing light footprints ($15k-$50k)."
    },
    {
      category: "Technical",
      question: "Do you support Virtual Production using LED Volumes?",
      answer: "Yes, we specialize in Unreal Engine 5 virtual art integration with camera tracking. This allows us to shot-film exotic worlds, sci-fi spacecrafts, or precise golden-hour illumination indefinitely on our stage without the high costs, weather issues, and logistical delays of physical travel."
    }
  ],
  services: [
    {
      name: "Commercial & Branded Masterclass",
      description: "Visual identity films, national television broadcasts, and internet-ready high-impact brand statements.",
      pricingEstimate: "$75,000 - $350,000+",
      equipmentStandard: "Arri Alexa 35 / Cooke Anamorphic Lenses, dedicated 20-person union crew",
      deliveryTime: "4 - 8 weeks"
    },
    {
      name: "Narrative Short & Pitch Development",
      description: "Bringing award-winning scripts and cinematic screenplays to life with premium aesthetic fidelity for studio bidding.",
      pricingEstimate: "$50,000 - $200,000 limit",
      equipmentStandard: "Sony Venice 2 & Atlas Orion Anamorphic series",
      deliveryTime: "6 - 12 weeks"
    },
    {
      name: "SEO Optimized Digital Sequences",
      description: "Creating premium commercial cuts tuned specifically for multi-aspect screens, complete with custom digital transcripts, targeted alt vectors, and SEO index packets.",
      pricingEstimate: "$15,000 - $45,000 range",
      equipmentStandard: "Sony Venice Dual-Base ISO setups designed for lean ultra-sharp assets",
      deliveryTime: "2 - 4 weeks"
    }
  ]
};
